spring.application.name=webprotege-snapshot-generator
server.port=7773

webprotege.rabbitmq.requestqueue=webprotege-snapshot-generator-queue
webprotege.rabbitmq.responsequeue=webprotege-snapshot-generator-response-queue
webprotege.rabbitmq.timeout=600000